--Create Role với chi tiết từ DAC (thêm bớt sau nếu có thể)
CREATE ROLE TruongPhong IDENTIFIED BY NeuCan; 
CREATE ROLE GiamDoc IDENTIFIED BY NeuCan; 
CREATE ROLE TruongChiNhanh IDENTIFIED BY NeuCan; 

--Grant các quyền cho Role
--Trưởng phòng
GRANT INSERT, UPDATE ON DUAN TO TruongPhong;
GRANT EXECUTE ON capNhatPhongBan TO TruongPhong;
--Giám đốc
 CREATE VIEW GiamDoc_XemTatCaDuAn 
    AS SELECT DUAN.MADA, DUAN.TENDA, DUAN.KINHPHI, PHONGBAN.TENPHONG, CHINHANH.TENCN, NHANVIEN.HOTEN AS TruongDA
        FROM PHONGBAN, DUAN, CHINHANH, NHANVIEN 
        WHERE PHONGBAN.MAPHONG = DUAN.PHONGCHUTRI 
            AND PHONGBAN.CHINHANH = CHINHANH.MACN
            AND DUAN.TRUONGDA = NHANVIEN.MANV;


GRANT SELECT ON GiamDoc_XemTatCaDuAn TO GiamDoc;

GRANT SELECT ON DUAN TO GiamDoc
GRANT SELECT ON PHONGBAN TO GiamDoc
GRANT SELECT ON CHINHANH TO GiamDoc
GRANT SELECT ON CHITIEU TO GiamDoc
-- Trưởng chi nhánh
GRANT EXECUTE ON capNhatChiNhanh TO TruongPhong;
