--DAC Chỉ trưởng phòng được phép cập nhật và thêm thông tin vào dự án
GRANT INSERT, UPDATE ON DUAN TO "10001";
GRANT INSERT, UPDATE ON DUAN TO "10002";
GRANT INSERT, UPDATE ON DUAN TO "10003";
GRANT INSERT, UPDATE ON DUAN TO "10004";
GRANT INSERT, UPDATE ON DUAN TO "10005";

